# Usa una imagen base de Maven para compilar tu aplicación y gestionar las dependencias
FROM maven:latest as build

# Copia todos los archivos al contenedor
COPY . /app/

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Compila tu aplicación y empaquétala en un archivo JAR
RUN mvn clean package

# Actualiza los paquetes e instala wget y tar (necesarios para descomprimir el JDK)
RUN apt-get update && apt-get install -y wget tar

# URL de descarga de OpenJDK 21 (ajusta la URL si es necesario)
ENV JDK_URL=https://download.java.net/java/GA/jdk21.0.2/f2283984656d49d69e91c558476027ac/13/GPL/openjdk-21.0.2_linux-x64_bin.tar.gz

# Descarga y descomprime OpenJDK 21
RUN mkdir -p /opt/jdk \
    && wget -q -O - $JDK_URL | tar -xz --strip-components=1 -C /opt/jdk

# Establece las variables de entorno para el JDK
ENV JAVA_HOME=/opt/jdk
ENV PATH=$PATH:$JAVA_HOME/bin

# Copia el archivo JAR generado por Maven al contenedor
COPY /target/SistemaMensajeria-1.0-SNAPSHOT-jar-with-dependencies.jar /app/app.jar

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Especifica cómo ejecutar tu aplicación cuando se inicie el contenedor
CMD ["java", "-jar", "app.jar"]
